#!/usr/bin/env bash
# One-shot DevOps learning lab bootstrap on Ubuntu (172.16.50.39 pattern).
# All control-plane code lives in this docker-devops repo — app repos are read-only build context.
#
# Usage (on the server):
#   cd /home/ienetworks/workspace/tools/docker-devops
#   bash scripts/bootstrap-learning-server.sh
#
# Options:
#   --fresh          run reset-server.sh --wipe-volumes first
#   --skip-clone     do not git clone/pull app repos
#   --skip-build     do not trigger Jenkins build-and-start
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SERVER_IP="${SERVER_IP:-172.16.50.39}"
DEPLOY_USER="${DEPLOY_USER:-ienetworks}"
WORKSPACE="${WORKSPACE:-/home/${DEPLOY_USER}/workspace}"
DEVOPS_ROOT="${DEVOPS_ROOT:-${WORKSPACE}/tools/docker-devops}"
COLLAB_SOURCE="${COLLABORATION_SOURCE:-${WORKSPACE}/company/SelamnewCollaboration}"

BE_BRANCH="${BE_BRANCH:-develop}"
FE_BRANCH="${FE_BRANCH:-develop}"
NES_BRANCH="${NES_BRANCH:-develop}"

FRESH=false
SKIP_CLONE=false
SKIP_BUILD=false

for arg in "$@"; do
  case "$arg" in
    --fresh) FRESH=true ;;
    --skip-clone) SKIP_CLONE=true ;;
    --skip-build) SKIP_BUILD=true ;;
  esac
done

log() { echo "==> $*"; }

# ---------------------------------------------------------------------------
# 0. Optional clean slate
# ---------------------------------------------------------------------------
if [[ "$FRESH" == true ]]; then
  log "Fresh start — wiping Docker volumes"
  bash "$ROOT/scripts/reset-server.sh" --wipe-volumes
fi

chmod +x "$ROOT/scripts/"*.sh "$ROOT/jenkins/bin/"*.sh "$ROOT/vault/scripts/"*.sh 2>/dev/null || true

# ---------------------------------------------------------------------------
# 1. OS packages
# ---------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker"
  sudo apt-get update -qq
  sudo apt-get install -y ca-certificates curl gnupg docker.io docker-compose-v2 unzip
  sudo usermod -aG docker "$USER" || true
elif ! command -v unzip >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y unzip
fi

if ! command -v nginx >/dev/null 2>&1; then
  log "Installing Nginx"
  sudo apt-get install -y nginx
fi

sudo systemctl enable --now docker nginx 2>/dev/null || true

DOCKER="docker"
if ! docker info >/dev/null 2>&1; then
  DOCKER="sudo docker"
fi

export DOCKER_GID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || echo 124)"

# ---------------------------------------------------------------------------
# 2. Workspace + app source (read-only — never edit app Jenkinsfiles)
# ---------------------------------------------------------------------------
mkdir -p "$WORKSPACE/tools" "$WORKSPACE/company" "$COLLAB_SOURCE"

clone_or_pull() {
  local dir="$1"
  local url="$2"
  local branch="$3"
  if [[ "$SKIP_CLONE" == true ]]; then
    log "Skip clone: $dir"
    return 0
  fi
  if [[ ! -d "$dir/.git" ]]; then
    log "Cloning $url → $dir"
    git clone "$url" "$dir"
  fi
  git -C "$dir" fetch origin "$branch" || git -C "$dir" fetch origin
  git -C "$dir" checkout "$branch" 2>/dev/null || git -C "$dir" checkout -B "$branch" "origin/$branch"
  git -C "$dir" pull --ff-only origin "$branch" 2>/dev/null || true
}

clone_or_pull "$COLLAB_SOURCE/backend" \
  "git@github.com:IE-Network-Solutions/selamnew-collaboration-backend.git" "$BE_BRANCH"
clone_or_pull "$COLLAB_SOURCE/frontend" \
  "git@github.com:IE-Network-Solutions/selamnew-collaboration-fe.git" "$FE_BRANCH"
clone_or_pull "$COLLAB_SOURCE/Notification-and-email-service" \
  "git@github.com:IE-Network-Solutions/Notification-and-email-service.git" "$NES_BRANCH"

# ---------------------------------------------------------------------------
# 3. Server config files (generated — not committed)
# ---------------------------------------------------------------------------
log "Writing collaboration/.env.docker"
cat >"$ROOT/collaboration/.env.docker" <<EOF
# Generated by bootstrap-learning-server.sh — do not commit
SERVER_IP=${SERVER_IP}
COLLABORATION_SOURCE=${COLLAB_SOURCE}

COLLABORATION_BACKEND_BRANCH=${BE_BRANCH}
COLLABORATION_FRONTEND_BRANCH=${FE_BRANCH}
COLLABORATION_NOTIFICATION_BRANCH=${NES_BRANCH}

COLLABORATION_WEBHOOK_DEPLOY=true

REGISTRY=127.0.0.1:5001
BACKEND_IMAGE_TAG=latest
FRONTEND_IMAGE_TAG=latest
NOTIFICATION_IMAGE_TAG=latest

FRONTEND_HOST_PORT=3000
BACKEND_HOST_PORT=5000
NOTIFICATION_HOST_PORT=8006
POSTGRES_HOST_PORT=5434
NOTIFICATION_POSTGRES_HOST_PORT=5435
REDIS_HOST_PORT=6381
ELASTICSEARCH_HOST_PORT=9200
ADMINER_HOST_PORT=8083
NOTIFICATION_ADMINER_HOST_PORT=8084

DB_USER=postgres
DB_PASSWORD=collab_secret
DB_NAME=selamnew-collab
NOTIFICATION_DB_NAME=selamnew-notification
EOF

log "Writing notification/.env.docker"
mkdir -p "$ROOT/notification/env"
cat >"$ROOT/notification/.env.docker" <<EOF
SERVER_IP=${SERVER_IP}
COLLABORATION_SOURCE=${COLLAB_SOURCE}
NOTIFICATION_BRANCH=${NES_BRANCH}
REGISTRY=127.0.0.1:5001
NOTIFICATION_IMAGE_TAG=latest
NOTIFICATION_HOST_PORT=8006
NOTIFICATION_POSTGRES_HOST_PORT=5435
NOTIFICATION_ADMINER_HOST_PORT=8084
NOTIFICATION_DB_USER=postgres
NOTIFICATION_DB_PASSWORD=nes_secret
NOTIFICATION_DB_NAME=selamnew-notification
EOF

ensure_env() {
  local example="$1"
  local target="$2"
  if [[ ! -f "$target" && -f "$example" ]]; then
    cp "$example" "$target"
    log "Created $(basename "$target") from example — fill secrets before FE build"
  fi
}

mkdir -p "$ROOT/collaboration/env"
ensure_env "$ROOT/collaboration/env/backend.env.example" "$ROOT/collaboration/env/backend.env"
ensure_env "$ROOT/collaboration/env/frontend.env.example" "$ROOT/collaboration/env/frontend.env"
ensure_env "$ROOT/notification/env/notification.env.example" "$ROOT/notification/env/notification.env"

# Patch browser-facing URLs for this server IP (non-secret)
if [[ -f "$ROOT/collaboration/env/backend.env" ]]; then
  sed -i "s|http://localhost:3000|http://${SERVER_IP}:3000|g" "$ROOT/collaboration/env/backend.env" || true
fi
if [[ -f "$ROOT/collaboration/env/frontend.env" ]]; then
  sed -i "s|http://localhost:5000|http://${SERVER_IP}:5000|g" "$ROOT/collaboration/env/frontend.env" || true
  sed -i "s|http://172.16.50.39:5000|http://${SERVER_IP}:5000|g" "$ROOT/collaboration/env/frontend.env" || true
  sed -i "s|http://172.16.50.39:3000|http://${SERVER_IP}:3000|g" "$ROOT/collaboration/env/frontend.env" || true
fi

# Jenkins admin + webhook tokens
mkdir -p "$ROOT/jenkins/secrets"
chmod 700 "$ROOT/jenkins/secrets"
if [[ ! -f "$ROOT/jenkins/secrets/admin.env" ]]; then
  cp "$ROOT/jenkins/secrets/admin.env.example" "$ROOT/jenkins/secrets/admin.env"
  sed -i "s/^JENKINS_ADMIN_PASS=.*/JENKINS_ADMIN_PASS=DevOps@${SERVER_IP//./}/" \
    "$ROOT/jenkins/secrets/admin.env" 2>/dev/null || true
fi
if [[ ! -f "$ROOT/jenkins/secrets/github-webhook-token.txt" ]]; then
  openssl rand -hex 16 >"$ROOT/jenkins/secrets/github-webhook-token.txt"
  chmod 600 "$ROOT/jenkins/secrets/github-webhook-token.txt"
fi
if [[ ! -f "$ROOT/jenkins/secrets/github-webhook-collab-token.txt" ]]; then
  openssl rand -hex 16 >"$ROOT/jenkins/secrets/github-webhook-collab-token.txt"
  chmod 600 "$ROOT/jenkins/secrets/github-webhook-collab-token.txt"
fi

# Export for Jenkins compose (bind-mount app source)
export COLLABORATION_SOURCE="$COLLAB_SOURCE"
export HOME="${HOME:-/home/${DEPLOY_USER}}"

# ---------------------------------------------------------------------------
# 4. Core stacks: registry → vault → secrets-room → jenkins → portainer
# ---------------------------------------------------------------------------
log "Starting local registry"
$DOCKER compose -f "$ROOT/registry/docker-compose.yml" up -d

log "Starting Vault + Secrets Room"
bash "$ROOT/scripts/bootstrap-server-vault-room.sh" || {
  log "Vault bootstrap had warnings — continuing"
}

log "Starting Jenkins"
$DOCKER compose -f "$ROOT/jenkins/docker-compose.yml" up -d --build

log "Starting Portainer"
$DOCKER compose -f "$ROOT/portainer/docker-compose.yml" up -d 2>/dev/null || true

log "Configuring Jenkins admin + jobs"
bash "$ROOT/jenkins/bin/setup-jenkins.sh"

# ---------------------------------------------------------------------------
# 5. Collaboration + notification infra (DB only — apps via Jenkins)
# ---------------------------------------------------------------------------
log "Starting collaboration infra (db, redis, elasticsearch, adminer)"
$DOCKER compose -f "$ROOT/collaboration/docker-compose.yml" \
  --env-file "$ROOT/collaboration/.env.docker" \
  up -d db redis elasticsearch adminer

log "Starting notification infra (db, adminer)"
$DOCKER compose -f "$ROOT/notification/docker-compose.yml" \
  --env-file "$ROOT/notification/.env.docker" \
  up -d db adminer 2>/dev/null || true

# ---------------------------------------------------------------------------
# 6. Nginx webhook proxy
# ---------------------------------------------------------------------------
log "Installing Nginx webhook proxy"
sudo cp "$ROOT/nginx/selamnew-vault-secrets.conf" /etc/nginx/sites-available/selamnew-devops-webhooks 2>/dev/null || true
if [[ -f /etc/nginx/sites-available/selamnew-devops-webhooks ]]; then
  sudo ln -sf /etc/nginx/sites-available/selamnew-devops-webhooks /etc/nginx/sites-enabled/selamnew-devops-webhooks
  sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  sudo nginx -t && sudo systemctl reload nginx
fi

# ---------------------------------------------------------------------------
# 7. Optional: build all three apps via Jenkins
# ---------------------------------------------------------------------------
if [[ "$SKIP_BUILD" != true ]]; then
  log "Triggering Jenkins build-and-start for backend + frontend + notification"
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/jenkins/secrets/admin.env" 2>/dev/null || true
  set +a
  JENKINS_URL="http://127.0.0.1:8080" bash "$ROOT/jenkins/bin/trigger-build.sh" collaboration-backend build-and-start || true
  JENKINS_URL="http://127.0.0.1:8080" bash "$ROOT/jenkins/bin/trigger-build.sh" collaboration-frontend build-and-start || true
  JENKINS_URL="http://127.0.0.1:8080" bash "$ROOT/jenkins/bin/trigger-build.sh" collaboration-notification build-and-start || true
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo "=============================================="
echo " DevOps Learning Lab — bootstrap complete"
echo "=============================================="
echo " Server:     ${SERVER_IP}"
echo " DevOps:     ${DEVOPS_ROOT}"
echo " App source: ${COLLAB_SOURCE} (read-only for builds)"
echo
echo " URLs:"
echo "  Jenkins:        http://${SERVER_IP}:8080"
echo "  Vault UI:       http://${SERVER_IP}:8200/ui"
echo "  Secrets Room:   http://${SERVER_IP}:8300"
echo "  Portainer:      https://${SERVER_IP}:9443"
echo "  Collab FE:      http://${SERVER_IP}:3000"
echo "  Collab BE:      http://${SERVER_IP}:5000/api/v1/health"
echo "  Notification:   http://${SERVER_IP}:8006"
echo "  Adminer (collab): http://${SERVER_IP}:8083"
echo "  Registry:       127.0.0.1:5001 (local only)"
echo
echo " Jenkins jobs (Build with Parameters → ACTION):"
echo "  collaboration-backend | collaboration-frontend | collaboration-notification"
echo "  collaboration-stack   | apply-vault-env | sync-devops-control-plane"
echo
echo " Learning guide: ${DEVOPS_ROOT}/LEARNING-GUIDE.md"
echo "=============================================="
$DOCKER ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
