# Lab frontend — FROM prebuilt lab-node (no apt). Fast after warm-lab-base.sh.
ARG LAB_NODE=127.0.0.1:5001/lab-node:20
FROM ${LAB_NODE} AS deps
WORKDIR /app
COPY package.json package-lock.json* .npmrc* ./
RUN npm config set fetch-timeout 600000 fetch-retries 5 \
  && npm ci --no-audit --no-fund --legacy-peer-deps 2>/dev/null \
    || npm install --no-audit --no-fund --legacy-peer-deps

FROM ${LAB_NODE} AS builder
WORKDIR /app
ARG NEXT_PUBLIC_COLLABORATION_URL=http://172.16.50.39:5000/api/v1
ARG NEXT_PUBLIC_WS_URL=http://172.16.50.39:5000
ARG NEXT_PUBLIC_API_URL=http://172.16.50.39:5000/api/v1
ARG NEXT_PUBLIC_API_BASE_URL=http://172.16.50.39:5000/api/v1
ARG NEXT_PUBLIC_COLLABORATION_SOCKET_URL=http://172.16.50.39:5000
ARG NEXT_PUBLIC_APP_URL=http://172.16.50.39:3000
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGE_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ENV NEXT_PUBLIC_COLLABORATION_URL=$NEXT_PUBLIC_COLLABORATION_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_COLLABORATION_SOCKET_URL=$NEXT_PUBLIC_COLLABORATION_SOCKET_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_AUTH_DOMAIN=$NEXT_PUBLIC_AUTH_DOMAIN
ENV NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID
ENV NEXT_PUBLIC_STORAGE_BUCKET=$NEXT_PUBLIC_STORAGE_BUCKET
ENV NEXT_PUBLIC_MESSAGE_SENDER_ID=$NEXT_PUBLIC_MESSAGE_SENDER_ID
ENV NEXT_PUBLIC_APP_ID=$NEXT_PUBLIC_APP_ID
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public
RUN NODE_OPTIONS=--max-old-space-size=4096 npx next build

FROM ${LAB_NODE} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3001
RUN useradd -m -u 1001 nextjs
COPY --from=deps --chown=nextjs:nextjs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nextjs /app/.next ./.next
COPY --from=builder --chown=nextjs:nextjs /app/public ./public
COPY --from=builder --chown=nextjs:nextjs /app/package.json ./package.json
USER nextjs
EXPOSE 3001
CMD ["npx", "next", "start", "-H", "0.0.0.0", "-p", "3001"]
